# Generated by Django 6.0.4 on 2026-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso (kg)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
