# Generated by Django 5.2.13 on 2026-04-24 00:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('envios', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomienda',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Encomienda', 'verbose_name_plural': 'Encomiendas'},
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='fecha_envio',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de Envío'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='envios_como_destinatario', to='clientes.cliente', verbose_name='Destinatario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega_est',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Real'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='remitente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='envios_como_remitente', to='clientes.cliente', verbose_name='Remitente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='rutas.ruta', verbose_name='Ruta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='volumen_cm3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volumen (cm³)'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('TRA', 'En tránsito'), ('ENT', 'Entregado'), ('DEV', 'Devuelto')], default='PEN', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo], verbose_name='Peso (kg)'),
        ),
        migrations.AlterModelTable(
            name='encomienda',
            table='encomiendas',
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('rutas_asignadas', models.ManyToManyField(blank=True, to='rutas.ruta', verbose_name='Rutas Asignadas')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
        migrations.AddField(
            model_name='encomienda',
            name='empleado_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='envios.empleado', verbose_name='Empleado que Registra'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PEN', 'Pendiente'), ('TRA', 'En tránsito'), ('ENT', 'Entregado'), ('DEV', 'Devuelto')], max_length=3, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('PEN', 'Pendiente'), ('TRA', 'En tránsito'), ('ENT', 'Entregado'), ('DEV', 'Devuelto')], max_length=3, verbose_name='Estado Nuevo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='envios.empleado', verbose_name='Empleado que registra')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='envios.encomienda', verbose_name='Encomienda')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'db_table': 'historial_estados',
            },
        ),
    ]
