# Generated by Django 5.2.13 on 2026-04-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Base')),
                ('dias_entrega', models.PositiveIntegerField(verbose_name='Días de Entrega')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'rutas',
            },
        ),
    ]
