# Generated by Django 5.2.13 on 2026-04-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carné de Extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=3, verbose_name='Tipo de Documento')),
                ('nro_doc', models.CharField(max_length=15, unique=True, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
    ]
